export default [
  'Addiction physicians',
  'Allergologist',
  'Anatomists',
  'Andrologists',
  'Anesthesiologists',
  'Cardiologists',
  'Coroners',
  'Dermatologists',
  'Diabetologists',
  'Dermatologists',
  'Emergency physicians',
  'Endocrinologists',
  'Euthanasia doctors',
  'Gastroenterologists',
  'General Practioners',
  'Geriatricians',
  'Gynaecologists',
  'Hematologists',
  'Hygienists',
  'Immunologists',
  'Infectious disease physicians',
  'Intensivists',
  'Internists',
  'Leprologists',
  'Military doctors',
  'Nephrologists',
  'Neurologists',
  'Neurosurgeons',
  'Nuclear medicine physicians',
  'Obstetricians',
  'Oncologists',
  'Ophthalmologists',
  'Osteopathic physicians',
  'Otolaryngologists',
  'Pain management physicians',
  'Palliative care physicians',
  'Parasitologists',
  'Pathologists',
  'Padiatricians',
  'Pharmacologists',
  'Podiatrists',
  'Psychiatrists',
  'Pulmonologists',
  'Radiologists',
  'Rehabilitation physicians',
  'Rheumatologists',
  'Sexologists',
  'Sports physicians',
  'Surgeons',
  'Toxicologists',
  'Traditional medicine practitioners',
  'Tropical physicians',
  'Urologists',
  'Virologists',
  ]